In [15]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('DREAMR.csv')

In [16]:
dataset.drop(columns=['Unnamed: 0'],inplace=True)
dataset = dataset.T

In [17]:
dataset.head()

,0,1,2,3,4,5,6,7,8,9,...,107513,107514,107515,107516,107517,107518,107519,107520,107521,107522
0,-2.051282,-21.538462,-13.333333,16.923077,14.358974,-13.846154,-12.820513,12.307692,25.641026,12.307692,...,-637.435897,-574.358974,-454.871795,-529.743590,-680.512821,-656.923077,-439.487179,4.0,3.0,2.0
1,8.205128,-1.025641,-11.282051,1.538462,13.333333,4.615385,-9.743590,-11.282051,4.615385,15.384615,...,-58.974359,-55.897436,-109.743590,-127.179487,-76.923077,10.769231,21.538462,3.0,3.0,1.0
2,-2.564103,15.897436,15.384615,2.051282,-5.128205,3.076923,19.487179,16.410256,-4.102564,-7.179487,...,262.051282,187.179487,185.128205,236.923077,234.358974,152.820513,110.769231,5.0,4.0,4.0
3,5.128205,-4.615385,-2.564103,4.615385,4.102564,2.564103,2.051282,1.025641,1.538462,4.102564,...,11.794872,-67.692308,-43.589744,64.615385,141.025641,98.974359,-1.538462,4.0,3.0,2.0
4,0.512821,-17.435897,-14.358974,7.692308,13.846154,-9.743590,-24.615385,-2.564103,18.461538,1.025641,...,357.435897,354.871795,265.128205,152.307692,138.974359,136.923077,122.564103,4.0,4.0,4.0

In [18]:
print(dataset.shape)

(414, 107523)

In [50]:
labels = dataset.drop(columns=list(range(0,107520)))
data = dataset.drop(columns=list(range(107520,107523)))

In [51]:
#zi = (xi – min(x)) / (max(x) – min(x)) * 100

min_val = min(data.min())
max_val = max(data.max())

data = (data - min_val) / (max_val - min_val) * 255
data = round(data)

In [52]:
data

,0,1,2,3,4,5,6,7,8,9,...,107510,107511,107512,107513,107514,107515,107516,107517,107518,107519
0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,...,117.0,118.0,118.0,117.0,118.0,120.0,119.0,116.0,116.0,120.0
1,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,...,128.0,127.0,126.0,127.0,127.0,126.0,126.0,127.0,128.0,128.0
2,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,...,130.0,131.0,133.0,133.0,131.0,131.0,132.0,132.0,131.0,130.0
3,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,...,126.0,128.0,129.0,128.0,127.0,127.0,129.0,130.0,130.0,128.0
4,128.0,128.0,128.0,128.0,128.0,128.0,127.0,128.0,128.0,128.0,...,133.0,132.0,133.0,134.0,134.0,133.0,131.0,130.0,130.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,...,127.0,127.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
410,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,127.0,...,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
411,127.0,127.0,126.0,126.0,126.0,126.0,126.0,126.0,126.0,125.0,...,129.0,129.0,129.0,129.0,129.0,129.0,128.0,128.0,128.0,128.0
412,128.0,128.0,128.0,128.0,128.0,128.0,127.0,127.0,128.0,128.0,...,127.0,127.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
413,129.0,130.0,130.0,130.0,130.0,130.0,130.0,131.0,131.0,131.0,...,128.0,128.0,129.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0

In [87]:
from PIL import Image
for i in range(0,414):
    img = data.iloc[i].to_numpy(dtype=np.uint8)
    img = img.reshape(280,384)
    image = Image.fromarray(img)
    name = str(i)+'img.png'
    image.save('img_dataset/'+name)

#import matplotlib.pyplot as plt
#plt.imshow(image,'gray')

In [ ]:
labels.to_csv("DREAMER_labels.csv")